<<<<<<< HEAD
imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

tools:
    external_code_coverage:
        timeout: 600 # Timeout in seconds.

    # Copy/Paste Detector
    php_cpd: true

    # Metrics
    php_pdepend: true

    # Some Metrics + Bug Detection/Auto-Fixes
    php_analyzer: true
=======
imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

tools:
    external_code_coverage:
        timeout: 600 # Timeout in seconds.
>>>>>>> upstream/master
